# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
