# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0004_auto_20160604_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
